// Search Function Code
(function (window, document, undefined) {
    function Narrower(inp, sel, disp, list) {
        this.inp = inp;
        this.sel = sel;
        this.disp = disp;
        this.list = list;
        this.last = ''; // last value on which we narrowed
    }
    

	Narrower.prototype = {
        init: function () {
            this.update('');
            this.addEvents();
        },
        addEvents: function () {
            var self;
            self = this;
            this.inp.addEventListener('keyup', function (e) {
                if (this.value !== self.last) {
                    self.last = this.value;
                    self.update(this.value);
                };
            });
            this.inp.focus();
        },
        update: function (str) {
            var ulist, rgxp;
            // optimization
            if (0 === str.length) {
                ulist = this.list;
            }
            else {
                ulist = [];
                // create rgxp
                rgxp = new RegExp(str, 'i'); // note: not Unicode-safe!
                // keep items that match
                for (var i = this.list.length - 1; i > -1; --i) {
                    if (null !== this.list[i].match(rgxp)) {
                        ulist.push(this.list[i]);
                    };
                };
            };
            this.updateSelect(ulist.sort());
            this.updateMatches(ulist.length);
        },
        updateSelect: function (arr) {
            var self, opts;
            self = this;
            this.sel.options.length = 0;
            opts = this.buildOpts(arr);
            opts.forEach(function (opt, idx) {
                self.sel.options[idx] = opt;
            });
        },
        buildOpts: function (arr) {
            var opts;
            opts = [];
            arr.forEach(function (val) {
                opts.push(new Option(val));
            });
            return opts;
        },
        updateMatches: function (len) {
            this.disp.innerHTML = 1 === len ? '1 match' : len + ' matches';
        }
    };

    // initialization
    var inp = document.querySelector('#nrwr');
    var sel = document.querySelector('#names');
    var disp = document.querySelector('#matches');
    var mytextbox = document.getElementById('nrwr');
    var mydropdown = document.getElementById('names');


    mydropdown.onchange = function () {
        mytextbox.value = this.value;
		testVar = mytextbox.value;
	}
    var list = (function () {
        var schoolArray = [
    'Abbotsford Public School',
    'Aberdeen Public School',
    'Abermain Public School',
    'Adaminaby Public School',
    'Adamstown Public School',
    'Adelong Public School',
    'Afterlee Public School',
    'Airds High School',
    'Ajuga School',
    'Albert Park Public School',
    'Albion Park High School',
    'Albion Park Public School',
    'Albion Park Rail Public School',
    'Albury High School',
    'Albury North Public School',
    'Albury Public School',
    'Albury West Public School',
    'Aldavilla Public School',
    'Alexandria Park Community School',
    'Alfords Point Public School',
    'Allambie Heights Public School',
    'Alma Public School',
    'Alstonville High School',
    'Alstonville Public School',
    'Ambarvale High School',
    'Ambarvale Public School',
    'Anna Bay Public School',
    'Annandale North Public School',
    'Annandale Public School',
    'Annangrove Public School',
    'Anson Street School',
    'Appin Public School',
    'Arcadia Public School',
    'Arcadia Vale Public School',
    'Ardlethan Central School',
    'Argenton Public School',
    'Ariah Park Central School',
    'Armidale City Public School',
    'Armidale High School',
    'Arncliffe Public School',
    'Arncliffe West Infants School',
    'Arndell School',
    'Arranounbai School',
    'Artarmon Public School',
    'Arthur Phillip High School',
    'Ashbury Public School',
    'Ashcroft High School',
    'Ashcroft Public School',
    'Ashfield Boys High School',
    'Ashfield Public School',
    'Ashford Central School',
    'Ashmont Public School',
    'Ashtonfield Public School',
    'Asquith Boys High School',
    'Asquith Girls High School',
    'Asquith Public School',
    'Athelstane Public School',
    'Attunga Public School',
    'Auburn Girls High School',
    'Auburn North Public School',
    'Auburn Public School',
    'Auburn West Public School',
    'Aurora College',
    'Austinmer Public School',
    'Austral Public School',
    'Australia Street Infants School',
    'Avalon Public School',
    'Avoca Beach Public School',
    'Avoca Public School',
    'Awaba Public School',
    'Awabakal Environmental Education Centre',
    'Balarang Public School',
    'Bald Blair Public School',
    'Bald Face Public School',
    'Balgowlah Heights Public School',
    'Balgowlah North Public School',
    'Balgownie Public School',
    'Ballimore Public School',
    'Ballina High School',
    'Ballina Public School',
    'Balmain Public School',
    'Balranald Central School',
    'Bangalow Public School',
    'Bangor Public School',
    'Banks Public School',
    'Banksia Road Public School',
    'Banksmeadow Public School',
    'Bankstown Girls High School',
    'Bankstown Hospital School',
    'Bankstown North Public School',
    'Bankstown Public School',
    'Bankstown Senior College',
    'Bankstown South Infants School',
    'Bankstown West Public School',
    'Banora Point High School',
    'Banora Point Public School',
    'Baradine Central School',
    'Bardwell Park Infants School',
    'Barellan Central School',
    'Bargo Public School',
    'Barham High School',
    'Barham Public School',
    'Barkers Vale Public School',
    'Barmedman Public School',
    'Barnier Public School',
    'Barnsley Public School',
    'Barooga Public School',
    'Barraba Central School',
    'Barrack Heights Public School',
    'Barrenjoey High School',
    'Barrington Public School',
    'Barwon Learning Centre',
    'Baryulgil Public School',
    'Bass High School',
    'Bass Hill Public School',
    'Bateau Bay Public School',
    'Batemans Bay High School',
    'Batemans Bay Public School',
    'Bates Drive School',
    'Bathurst Public School',
    'Bathurst South Public School',
    'Bathurst West Public School',
    'Batlow Technology School',
    'Baulkham Hills High School',
    'Baulkham Hills North Public School',
    'Beacon Hill Public School',
    'Beaumont Hills Public School',
    'Beaumont Road Public School',
    'Beauty Point Public School',
    'Beckom Public School',
    'Bedgerebong Public School',
    'Beechwood Public School',
    'Beecroft Public School',
    'Beelbangera Public School',
    'Bega High School',
    'Bega Valley Public School',
    'Belair Public School',
    'Bellambi Public School',
    'Bellata Public School',
    'Bellbird Public School',
    'Bellbrook Public School',
    'Bellevue Hill Public School',
    'Bellingen High School',
    'Bellingen Public School',
    'Belltrees Public School',
    'Belmont High School',
    'Belmont North Public School',
    'Belmont Public School',
    'Belmore Boys High School',
    'Belmore North Public School',
    'Belmore South Public School',
    'Belrose Public School',
    'Bemboka Public School',
    'Ben Lomond Public School',
    'Ben Venue Public School',
    'Bendemeer Public School',
    'Bennett Road Public School',
    'Berala Public School',
    'Beresfield Public School',
    'Beresford Road Public School',
    'Berinba Public School',
    'Berkeley Public School',
    'Berkeley Vale Public School',
    'Berkeley West Public School',
    'Bermagui Public School',
    'Berowra Public School',
    'Berridale Public School',
    'Berrigan Public School',
    'Berrima Public School',
    'Berry Public School',
    'Bert Oldfield Public School',
    'Beverley Park School',
    'Beverly Hills Girls High School',
    'Beverly Hills North Public School',
    'Beverly Hills Public School',
    'Bexhill Public School',
    'Bexley North Public School',
    'Bexley Public School',
    'Bibbenluke Public School',
    'Biddabah Public School',
    'Bidwill Public School',
    'Bigga Public School',
    'Bilambil Public School',
    'Bilgola Plateau Public School',
    'Billabong High School',
    'Bilpin Public School',
    'Binalong Public School',
    'Binda Public School',
    'Bingara Central School',
    'Binnaway Central School',
    'Binya Public School',
    'Biraban Public School',
    'Birchgrove Public School',
    'Birrong Boys High School',
    'Birrong Girls High School',
    'Birrong Public School',
    'Black Hill Public School',
    'Black Mountain Public School',
    'Black Springs Public School',
    'Blackalls Park Public School',
    'Blackett Public School',
    'Blackheath Public School',
    'Blacksmiths Public School',
    'Blacktown Boys High School',
    'Blacktown Girls High School',
    'Blacktown North Public School',
    'Blacktown South Public School',
    'Blacktown West Public School',
    'Blackville Public School',
    'Blackwell Public School',
    'Blairmount Public School',
    'Blakebrook Public School',
    'Blakehurst High School',
    'Blakehurst Public School',
    'Blandford Public School',
    'Blaxcell Street Public School',
    'Blaxland East Public School',
    'Blaxland High School',
    'Blaxland Public School',
    'Blayney High School',
    'Blayney Public School',
    'Bletchington Public School',
    'Bligh Park Public School',
    'Blighty Public School',
    'Blue Haven Public School',
    'Boambee Public School',
    'Bobin Public School',
    'Bobs Farm Public School',
    'Bodalla Public School',
    'Bogan Gate Public School',
    'Bogangar Public School',
    'Boggabilla Central School',
    'Boggabri Public School',
    'Bolwarra Public School',
    'Bomaderry High School',
    'Bomaderry Public School',
    'Bombala High School',
    'Bombala Public School',
    'Bonalbo Central School',
    'Bondi Beach Public School',
    'Bondi Public School',
    'Bongongo Public School',
    'Bonnells Bay Public School',
    'Bonnet Bay Public School',
    'Bonnyrigg Heights Public School',
    'Bonnyrigg High School',
    'Bonnyrigg Public School',
    'Bonshaw Public School',
    'Bonville Public School',
    'Boolaroo Public School',
    'Booligal Public School',
    'Boomi Public School',
    'Booragul Public School',
    'Booral Public School',
    'Boorowa Central School',
    'Boree Creek Public School',
    'Borenore Public School',
    'Boronia Park Public School',
    'Bossley Park High School',
    'Bossley Park Public School',
    'Botany Bay Environmental Education Centre',
    'Botany Public School',
    'Bourke High School',
    'Bourke Public School',
    'Bourke Street Public School',
    'Bourke-Walgett School of Distance Education',
    'Bournda Environmental Education Centre',
    'Bowen Public School',
    'Bowning Public School',
    'Bowral High School',
    'Bowral Public School',
    'Bowraville Central School',
    'Bradbury Public School',
    'Braddock Public School',
    'Bradfordville Public School',
    'Braidwood Central School',
    'Branxton Public School',
    'Breadalbane Public School',
    'Bredbo Public School',
    'Brewarrina Central School',
    'Brewongle Environmental Education Centre',
    'Briar Road Public School',
    'Bribbaree Public School',
    'Bridge Road School',
    'Brighton-Le-Sands Public School',
    'Bringelly Public School',
    'Brisbane Water Secondary College Umina Campus',
    'Brisbane Water Secondary College Woy Woy Campus',
    'Brisbania Public School',
    'Broadwater Public School',
    'Brocklesby Public School',
    'Broderick Gillawarna School',
    'Broke Public School',
    'Broken Hill High School',
    'Broken Hill North Public School',
    'Broken Hill Public School',
    'Bronte Public School',
    'Brooke Avenue Public School',
    'Brooklyn Public School',
    'Brookvale Public School',
    'Broulee Public School',
    'Brungle Public School',
    'Brunswick Heads Public School',
    'Budawang School',
    'Budgewoi Public School',
    'Bulahdelah Central School',
    'Bullarah Public School',
    'Bulli High School',
    'Bulli Public School',
    'Bullimbal School',
    'Bundanoon Public School',
    'Bundarra Central School',
    'Bundeena Public School',
    'Bungendore Public School',
    'Bungwahl Public School',
    'Buninyong Public School',
    'Bunnaloo Public School',
    'Burke Ward Public School',
    'Burnside Public School',
    'Buronga Public School',
    'Burraga Public School',
    'Burraneer Bay Public School',
    'Burrawang Public School',
    'Burren Junction Public School',
    'Burringbar Public School',
    'Burrumbuttock Public School',
    'Burwood Girls High School',
    'Burwood Public School',
    'Busby Public School',
    'Busby West Public School',
    'Buxton Public School',
    'Byron Bay High School',
    'Byron Bay Public School',
    'Cabbage Tree Island Public School',
    'Cabramatta High School',
    'Cabramatta Public School',
    'Cabramatta West Public School',
    'Cabramurra Public School',
    'Caddies Creek Public School',
    'Cairnsfoot School',
    'Calare Public School',
    'Caldera School',
    'Callaghan College Jesmond Campus',
    'Callaghan College Wallsend Campus',
    'Callaghan College Waratah Technology Campus',
    'Callala Public School',
    'Cambewarra Public School',
    'Cambridge Gardens Public School',
    'Cambridge Park High School',
    'Cambridge Park Public School',
    'Camden Haven High School',
    'Camden High School',
    'Camden Park Environmental Education Centre',
    'Camden Public School',
    'Camden South Public School',
    'Camdenville Public School',
    'Cammeray Public School',
    'Cammeraygal High School',
    'Campbell House School',
    'Campbellfield Public School',
    'Campbelltown East Public School',
    'Campbelltown North Public School',
    'Campbelltown Performing Arts High School',
    'Campbelltown Public School',
    'Campsie Public School',
    'Candelo Public School',
    'Caniaba Public School',
    'Canley Heights Public School',
    'Canley Vale High School',
    'Canley Vale Public School',
    'Canobolas Public School',
    'Canobolas Rural Technology High School',
    'Canowindra High School',
    'Canowindra Public School',
    'Canterbury Boys High School',
    'Canterbury Girls High School',
    'Canterbury Public School',
    'Canterbury South Public School',
    'Canterbury Vale School',
    'Capertee Public School',
    'Captains Flat Public School',
    'Caragabal Public School',
    'Carcoar Public School',
    'Cardiff High School',
    'Cardiff North Public School',
    'Cardiff Public School',
    'Cardiff South Public School',
    'Carenne School',
    'Cargo Public School',
    'Carinda Public School',
    'Caringbah High School',
    'Caringbah North Public School',
    'Caringbah Public School',
    'Carinya School',
    'Carlingford High School',
    'Carlingford Public School',
    'Carlingford West Public School',
    'Carlton Public School',
    'Carlton South Public School',
    'Caroline Chisholm School',
    'Carool Public School',
    'Carramar Public School',
    'Carrathool Public School',
    'Carrington Public School',
    'Carroll Public School',
    'Cartwright Public School',
    'Cascade Environmental Education Centre',
    'Casino High School',
    'Casino Public School',
    'Casino West Public School',
    'Cassilis Public School',
    'Castle Cove Public School',
    'Castle Hill High School',
    'Castle Hill Public School',
    'Castlereagh Public School',
    'Casuarina School',
    'Casula High School',
    'Casula Public School',
    'Cattai Public School',
    'Caves Beach Public School',
    'Cawdor Public School',
    'Cecil Hills High School',
    'Cecil Hills Public School',
    'Centaur Public School',
    'Centennial Park School',
    'Central Mangrove Public School',
    'Central Tilba Public School',
    'Cessnock East Public School',
    'Cessnock High School',
    'Cessnock Public School',
    'Cessnock West Public School',
    'Chalmers Road School',
    'Chandler Public School',
    'Charlestown East Public School',
    'Charlestown Public School',
    'Charlestown South Public School',
    'Chatham High School',
    'Chatham Public School',
    'Chatswood High School',
    'Chatswood Public School',
    'Chatsworth Island Public School',
    'Cheltenham Girls High School',
    'Cherrybrook Public School',
    'Cherrybrook Technology High School',
    'Chertsey Primary School',
    'Chester Hill High School',
    'Chester Hill North Public School',
    'Chester Hill Public School',
    'Chifley College Bidwill Campus',
    'Chifley College Dunheved Campus',
    'Chifley College Mount Druitt Campus',
    'Chifley College Senior Campus',
    'Chifley College Shalvey Campus',
    'Chifley Public School',
    'Chillingham Public School',
    'Chipping Norton Public School',
    'Chittaway Bay Public School',
    'Chullora Public School',
    'Clairgate Public School',
    'Clare Public School',
    'Claremont Meadows Public School',
    'Clarence Town Public School',
    'Clarke Road School',
    'Claymore Public School',
    'Clemton Park Public School',
    'Clergate Public School',
    'Cleveland Street Intensive English High School',
    'Clovelly Public School',
    'Clunes Public School',
    'Coal Point Public School',
    'Cobar High School',
    'Cobar Public School',
    'Cobargo Public School',
    'Cobbitty Public School',
    'Coffee Camp Public School',
    'Coffs Harbour High School',
    'Coffs Harbour Learning Centre',
    'Coffs Harbour Public School',
    'Coffs Harbour Senior College',
    'Coleambally Central School',
    'Coledale Public School',
    'Collarenebri Central School',
    'Collaroy Plateau Public School',
    'Collector Public School',
    'Collingullie Public School',
    'Collins Creek Public School',
    'Colo Heights Public School',
    'Colo High School',
    'Colo Vale Public School',
    'Colyton High School',
    'Colyton Public School',
    'Comboyne Public School',
    'Comleroy Road Public School',
    'Como Public School',
    'Como West Public School',
    'Conargo Public School',
    'Concord High School',
    'Concord Public School',
    'Concord West Public School',
    'Condell Park High School',
    'Condell Park Public School',
    'Condobolin High School',
    'Condobolin Public School',
    'Condong Public School',
    'Congewai Public School',
    'Coniston Public School',
    'Connells Point Public School',
    'Conservatorium High School',
    'Cooerwull Public School',
    'Coogee Public School',
    'Cook School',
    'Coolah Central School',
    'Coolamon Central School',
    'Coolongolook Public School',
    'Cooma North Public School',
    'Cooma Public School',
    'Coomealla High School',
    'Coonabarabran High School',
    'Coonabarabran Public School',
    'Coonamble High School',
    'Coonamble Public School',
    'Coopernook Public School',
    'Coorabell Public School',
    'Cooranbong Public School',
    'Cootamundra High School',
    'Cootamundra Public School',
    'Copacabana Public School',
    'Copmanhurst Public School',
    'Coraki Public School',
    'Coramba Public School',
    'Coreen School',
    'Corindi Public School',
    'Corndale Public School',
    'Corowa High School',
    'Corowa Public School',
    'Corowa South Public School',
    'Corrimal East Public School',
    'Corrimal High School',
    'Corrimal Public School',
    'Coutts Crossing Public School',
    'Cowan Public School',
    'Cowper Public School',
    'Cowra High School',
    'Cowra Public School',
    'Crabbes Creek Public School',
    'Cranebrook High School',
    'Crawford Public School',
    'Crescent Head Public School',
    'Crestwood High School',
    'Crestwood Public School',
    'Cringila Public School',
    'Cromehurst School',
    'Cromer Public School',
    'Cronulla High School',
    'Cronulla Public School',
    'Cronulla South Public School',
    'Crookwell High School',
    'Crookwell Public School',
    'Croppa Creek Public School',
    'Crossmaglen Public School',
    'Crown Street Public School',
    'Croydon Park Public School',
    'Croydon Public School',
    'Crystal Creek Public School',
    'Cudal Public School',
    'Cudgegong Valley Public School',
    'Cudgen Public School',
    'Culburra Public School',
    'Culcairn Public School',
    'Cullen Bullen Public School',
    'Cumberland High School',
    'Cumnock Public School',
    'Cundletown Public School',
    'Curl Curl North Public School',
    'Curlewis Public School',
    'Currabubula Public School',
    'Curran Public School',
    'Currans Hill Public School',
    'Daceyville Public School',
    'Dalgety Public School',
    'Dalmeny Public School',
    'Dalton Public School',
    'Dapto High School',
    'Dapto Public School',
    'Darcy Road Public School',
    'Dareton Public School',
    'Darlinghurst Public School',
    'Darlington Point Public School',
    'Darlington Public School',
    'Davidson High School',
    'Dawson Public School',
    'Dee Why Public School',
    'Deepwater Public School',
    'Delegate Public School',
    'Delungra Public School',
    'Deniliquin High School',
    'Deniliquin North Public School',
    'Deniliquin South Public School',
    'Denison College of Secondary Education  Bathurst High Campus',
    'Denison College of Secondary Education  Kelso High Campus',
    'Denistone East Public School',
    'Denman Public School',
    'Dobroyd Point Public School',
    'Doonside High School',
    'Doonside Public School',
    'Dora Creek Public School',
    'Dorchester School',
    'Dorrigo High School',
    'Dorrigo Public School',
    'Dorroughby Environmental Education Centre',
    'Double Bay Public School',
    'Doubtful Creek Public School',
    'Douglas Park Public School',
    'Drake Public School',
    'Drummond Memorial Public School',
    'Drummoyne Public School',
    'Dubbo College Delroy Campus',
    'Dubbo College Senior Campus',
    'Dubbo College South Campus',
    'Dubbo North Public School',
    'Dubbo Public School',
    'Dubbo School of Distance Education',
    'Dubbo South Public School',
    'Dubbo West Public School',
    'Dudley Public School',
    'Dulwich High School of Visual Arts and Design',
    'Dulwich Hill Public School',
    'Dundas Public School',
    'Dundurrabin Public School',
    'Dunedoo Central School',
    'Dungay Public School',
    'Dungog High School',
    'Dungog Public School',
    'Dungowan Public School',
    'Dunoon Public School',
    'Dural Public School',
    'Duranbah Public School',
    'Duri Public School',
    'Durrumbul Public School',
    'Duval High School',
    'E A Southee Public School',
    'Eagle Vale High School',
    'Earlwood Public School',
    'East Hills Boys High School',
    'East Hills Girls Technology High School',
    'East Hills Public School',
    'Eastern Creek Public School',
    'Eastlakes Public School',
    'Eastwood Heights Public School',
    'Eastwood Public School',
    'Ebenezer Public School',
    'Ebor Public School',
    'Eden Marine High School',
    'Eden Public School',
    'Edensor Park Public School',
    'Edgeware School',
    'Edgeworth Heights Public School',
    'Edgeworth Public School',
    'Edward Public School',
    'Eglinton Public School',
    'Elands Public School',
    'Elanora Heights Public School',
    'Elderslie High School',
    'Elderslie Public School',
    'Eleebana Public School',
    'Elermore Vale Public School',
    'Elizabeth Macarthur High School',
    'Ellalong Public School',
    'Ellerston Public School',
    'Ellison Public School',
    'Eltham Public School',
    'Emerton Public School',
    'Emmaville Central School',
    'Empire Bay Public School',
    'Empire Vale Public School',
    'Emu Heights Public School',
    'Emu Plains Public School',
    'Endeavour Sports High School',
    'Enfield Public School',
    'Engadine High School',
    'Engadine Public School',
    'Engadine West Public School',
    'Enngonia Public School',
    'Epping Boys High School',
    'Epping Heights Public School',
    'Epping North Public School',
    'Epping Public School',
    'Epping West Public School',
    'Erina Heights Public School',
    'Erina High School',
    'Ermington Public School',
    'Ermington West Public School',
    'Erskine Park High School',
    'Erskineville Public School',
    'Eschol Park Public School',
    'Ettalong Public School',
    'Euabalong West Public School',
    'Euchareena Public School',
    'Eugowra Public School',
    'Eumungerie Public School',
    'Eungai Public School',
    'Eureka Public School',
    'Eurongilly Public School',
    'Euston Public School',
    'Evans High School',
    'Evans River Community School',
    'Excelsior Public School',
    'Exeter Public School',
    'Fairfax Public School',
    'Fairfield Heights Public School',
    'Fairfield High School',
    'Fairfield Public School',
    'Fairfield West Public School',
    'Fairvale High School',
    'Fairvale Public School',
    'Fairy Meadow Public School',
    'Falls Creek Public School',
    'Farmborough Road Public School',
    'Farrer Memorial Agricultural High School',
    'Fassifern Public School',
    'Faulconbridge Public School',
    'Fennell Bay Public School',
    'Fern Bay Public School',
    'Ferncourt Public School',
    'Fernleigh Public School',
    'Field of Mars Environmental Education Centre',
    'Figtree Heights Public School',
    'Figtree High School',
    'Figtree Public School',
    'Fingal Head Public School',
    'Finley High School',
    'Finley Public School',
    'Fisher Road School',
    'Five Dock Public School',
    'Five Islands School',
    'Five Islands Secondary College',
    'Flinders Public School',
    'Floraville Public School',
    'Forbes High School',
    'Forbes North Public School',
    'Forbes Public School',
    'Forest Hill Public School',
    'Forest Lodge Public School',
    'Forestville Public School',
    'Forster Public School',
    'Fort Street High School',
    'Fort Street Public School',
    'Fowler Road School',
    'Francis Greenway High School',
    'Frank Partridge VC Public School',
    'Franklin Public School',
    'Frederickton Public School',
    'Freemans Reach Public School',
    'Frenchs Forest Public School',
    'G S Kidd Memorial School',
    'Gadara School',
    'Galston High School',
    'Galston Public School',
    'Ganmain Public School',
    'Garah Public School',
    'Garden Suburb Public School',
    'Gardeners Road Public School',
    'George Anderson Walpole School',
    'George Bass School',
    'Georges Hall Public School',
    'Georges River College Hurstville Boys Campus',
    'Georges River College Oatley Senior Campus',
    'Georges River College Peakhurst Campus',
    'Georges River College Penshurst Girls Campus',
    'Georges River Environmental Education Centre',
    'Gerogery Public School',
    'Gerringong Public School',
    'Geurie Public School',
    'Gibberagong Environmental Education Centre',
    'Gilgai Public School',
    'Gilgandra High School',
    'Gilgandra Public School',
    'Gillieston Public School',
    'Gillwinga Public School',
    'Girilambone Public School',
    'Girrakool School',
    'Girraween High School',
    'Girraween Public School',
    'Gladesville Public School',
    'Gladstone Public School',
    'Glebe Public School',
    'Glen Alice Public School',
    'Glen Innes High School',
    'Glen Innes Public School',
    'Glen Innes West Infants School',
    'Glen William Public School',
    'Glenbrook Public School',
    'Glendale East Public School',
    'Glendale High School',
    'Glendenning Public School',
    'Glendore Public School',
    'Glenfield Park School',
    'Glenfield Public School',
    'Glenhaven Public School',
    'Glenmore Park High School',
    'Glenmore Park Public School',
    'Glenmore Road Public School',
    'Glenorie Public School',
    'Glenquarry Public School',
    'Glenreagh Public School',
    'Glenroi Heights Public School',
    'Glenroy Public School',
    'Glenvale School',
    'Glenwood High School',
    'Glenwood Public School',
    'Glossodia Public School',
    'Gloucester High School',
    'Gloucester Public School',
    'Gol Gol Public School',
    'Goodooga Central School',
    'Goolgowi Public School',
    'Goolma Public School',
    'Goolmangar Public School',
    'Gooloogong Public School',
    'Goonellabah Public School',
    'Goonengerry Public School',
    'Gordon East Public School',
    'Gordon West Public School',
    'Gorokan High School',
    'Gorokan Public School',
    'Gosford East Public School',
    'Gosford High School',
    'Gosford Public School',
    'Goulburn East Public School',
    'Goulburn High School',
    'Goulburn North Public School',
    'Goulburn Public School',
    'Goulburn South Public School',
    'Goulburn West Public School',
    'Governor Philip King Public School',
    'Grafton High School',
    'Grafton Public School',
    'Grahamstown Public School',
    'Gralee School',
    'Granville Boys High School',
    'Granville East Public School',
    'Granville Public School',
    'Granville South Creative and Performing Arts High School',
    'Granville South Public School',
    'Gravesend Public School',
    'Grays Point Public School',
    'Great Lakes College Forster Campus',
    'Great Lakes College Senior Campus',
    'Great Lakes College Tuncurry Campus',
    'Green Hill Public School',
    'Green Square School',
    'Green Valley Public School',
    'Greenacre Public School',
    'Greenethorpe Public School',
    'Greenway Park Public School',
    'Greenwell Point Public School',
    'Greenwich Public School',
    'Grenfell Public School',
    'Gresford Public School',
    'Greta Public School',
    'Greystanes High School',
    'Greystanes Public School',
    'Griffith East Public School',
    'Griffith High School',
    'Griffith North Public School',
    'Griffith Public School',
    'Grose View Public School',
    'Guildford Public School',
    'Guildford West Public School',
    'Guise Public School',
    'Gulargambone Central School',
    'Gulgong High School',
    'Gulgong Public School',
    'Gulmarrad Public School',
    'Gum Flat Public School',
    'Gundagai High School',
    'Gundagai Public School',
    'Gundagai South Public School',
    'Gundaroo Public School',
    'Gunnedah High School',
    'Gunnedah Public School',
    'Gunnedah South Public School',
    'Gunning Public School',
    'Guyra Central School',
    'Gwabegar Public School',
    'Gwandalan Public School',
    'Gwynneville Public School',
    'Gymea Bay Public School',
    'Gymea North Public School',
    'Gymea Technology High School',
    'Haberfield Public School',
    'Halinda School',
    'Hallidays Point Public School',
    'Hambledon Public School',
    'Hamilton North Public School',
    'Hamilton Public School',
    'Hamilton South Public School',
    'Hammondville Public School',
    'Hampden Park Public School',
    'Hampton Public School',
    'Hannam Vale Public School',
    'Hannans Road Public School',
    'Hanwood Public School',
    'Harbord Public School',
    'Harcourt Public School',
    'Hargraves Public School',
    'Harrington Park Public School',
    'Harrington Public School',
    'Harrington Street Public School',
    'Harwood Island Public School',
    'Hassall Grove Public School',
    'Hastings Public School',
    'Havenlee School',
    'Hawkesbury High School',
    'Hay Public School',
    'Hay War Memorial High School',
    'Hayes Park Public School',
    'Hazelbrook Public School',
    'Heathcote East Public School',
    'Heathcote High School',
    'Heathcote Public School',
    'Heaton Public School',
    'Hebersham Public School',
    'Heckenberg Public School',
    'Helensburgh Public School',
    'Henry Fulton Public School',
    'Henry Kendall High School',
    'Henty Public School',
    'Hermidale Public School',
    'Hernani Public School',
    'Herons Creek Public School',
    'Highlands School',
    'Hill End Public School',
    'Hill Top Public School',
    'Hillsborough Public School',
    'Hillside Public School',
    'Hillston Central School',
    'Hilltop Road Public School',
    'Hillvue Public School',
    'Hinchinbrook Public School',
    'Hinton Public School',
    'Hobartville Public School',
    'Holbrook Public School',
    'Holgate Public School',
    'Holman Place School',
    'Holmwood Public School',
    'Holroyd High School',
    'Holroyd School',
    'Holsworthy High School',
    'Holsworthy Public School',
    'Homebush Boys High School',
    'Homebush Public School',
    'Homebush West Public School',
    'HopeTown School',
    'Hornsby Girls High School',
    'Hornsby Heights Public School',
    'Hornsby North Public School',
    'Hornsby South Public School',
    'Horsley Park Public School',
    'Howlong Public School',
    'Hoxton Park High School',
    'Hoxton Park Public School',
    'Hume Public School',
    'Humula Public School',
    'Hunter River Community School',
    'Hunter River High School',
    'Hunter School of Performing Arts',
    'Hunter Sports High School',
    'Hunters Hill High School',
    'Hunters Hill Public School',
    'Huntingdon Public School',
    'Hurlstone Agricultural High School',
    'Hurstville Grove Infants School',
    'Hurstville Public School',
    'Hurstville South Public School',
    'Huskisson Public School',
    'Ilford Public School',
    'Illabo Public School',
    'Illaroo Road Public School',
    'Illawarra Environmental Education Centre',
    'Illawarra Hospital School',
    'Illawarra Sports High School',
    'Illawong Public School',
    'Iluka Public School',
    'Induna School',
    'Ingleburn High School',
    'Ingleburn North Public School',
    'Ingleburn Public School',
    'Inverell High School',
    'Inverell Public School',
    'Iona Public School',
    'Ironbark Ridge Public School',
    'Irrawang High School',
    'Irrawang Public School',
    'Islington Public School',
    'Ivanhoe Central School',
    'J J Cahill Memorial High School',
    'Jamberoo Public School',
    'James Busby High School',
    'James Cook Boys High School',
    'James Erskine Public School',
    'James Fallon High School',
    'James Meehan High School',
    'James Ruse Agricultural High School',
    'Jamison High School',
    'Jamisontown Public School',
    'Jannali East Public School',
    'Jannali Public School',
    'Jasper Road Public School',
    'Jennings Public School',
    'Jerangle Public School',
    'Jerilderie Public School',
    'Jerrabomberra Public School',
    'Jerrys Plains Public School',
    'Jesmond Public School',
    'Jewells Primary School',
    'Jiggi Public School',
    'Jilliby Public School',
    'Jindabyne Central School',
    'Jindera Public School',
    'John Brotchie Nursery School',
    'John Edmondson High School',
    'John Hunter Hospital School',
    'John Palmer Public School',
    'John Purchase Public School',
    'John Warby Public School',
    'Johns River Public School',
    'Jugiong Public School',
    'Junee High School',
    'Junee North Public School',
    'Junee Public School',
    'Kadina High School',
    'Kahibah Public School',
    'Kalinda School',
    'Kambora Public School',
    'Kanahooka High School',
    'Kandeer School',
    'Kandos High School',
    'Kandos Public School',
    'Kangaloon Public School',
    'Kangaroo Valley Public School',
    'Kanwal Public School',
    'Kapooka Public School',
    'Karabar High School',
    'Karangi Public School',
    'Kareela Public School',
    'Kariong Mountains High School',
    'Kariong Public School',
    'Karningul School',
    'Karonga School',
    'Karuah Public School',
    'Katoomba High School',
    'Katoomba North Public School',
    'Katoomba Public School',
    'Kearns Public School',
    'Kearsley Public School',
    'Kegworth Public School',
    'Keira High School',
    'Keiraville Public School',
    'Kellys Plains Public School',
    'Kellyville High School',
    'Kellyville Public School',
    'Kellyville Ridge Public School',
    'Kelso Public School',
    'Kemblawarra Public School',
    'Kemps Creek Public School',
    'Kempsey East Public School',
    'Kempsey High School',
    'Kempsey South Public School',
    'Kempsey West Public School',
    'Kendall Public School',
    'Kensington Public School',
    'Kent Road Public School',
    'Kenthurst Public School',
    'Kentlyn Public School',
    'Kentucky Public School',
    'Khancoban Public School',
    'Kiama High School',
    'Kiama Public School',
    'Killara High School',
    'Killara Public School',
    'Killarney Heights High School',
    'Killarney Heights Public School',
    'Killarney Vale Public School',
    'Kinchela Public School',
    'Kincumber High School',
    'Kincumber Public School',
    'King Park Public School',
    'King Street Public School',
    'Kings Langley Public School',
    'Kingscliff High School',
    'Kingscliff Public School',
    'Kingsgrove High School',
    'Kingsgrove North High School',
    'Kingsgrove Public School',
    'Kingstown Public School',
    'Kingswood High School',
    'Kingswood Park Public School',
    'Kingswood Public School',
    'Kingswood South Public School',
    'Kirkton Public School',
    'Kirrawee High School',
    'Kirrawee Public School',
    'Kitchener Public School',
    'Kogarah High School',
    'Kogarah Public School',
    'Koonawarra Public School',
    'Koorawatha Public School',
    'Kooringal High School',
    'Kooringal Public School',
    'Kootingal Public School',
    'Kororo Public School',
    'Kotara High School',
    'Kotara School',
    'Kotara South Public School',
    'Krambach Public School',
    'Kulnura Public School',
    'Ku-ring-gai High School',
    'Kurmond Public School',
    'Kurnell Public School',
    'Kurrajong East Public School',
    'Kurrajong North Public School',
    'Kurrajong Public School',
    'Kurrambee School',
    'Kurri Kurri High School',
    'Kurri Kurri Public School',
    'Kyeemagh Infants School',
    'Kyogle High School',
    'Kyogle Public School',
    'La Perouse Public School',
    'Ladysmith Public School',
    'Laggan Public School',
    'Laguna Public School',
    'Laguna Street Public School',
    'Lake Albert Public School',
    'Lake Cargelligo Central School',
    'Lake Cathie Public School',
    'Lake Heights Public School',
    'Lake Illawarra High School',
    'Lake Illawarra South Public School',
    'Lake Macquarie High School',
    'Lake Munmorah High School',
    'Lake Munmorah Public School',
    'Lake Wyangan Public School',
    'Lakelands Public School',
    'Lakemba Public School',
    'Lakeside School',
    'Lalor Park Public School',
    'Lambton High School',
    'Lambton Public School',
    'Lane Cove Public School',
    'Lane Cove West Public School',
    'Lansdowne Public School',
    'Lansvale East Public School',
    'Lansvale Public School',
    'Lapstone Public School',
    'Largs Public School',
    'Larnook Public School',
    'Laurieton Public School',
    'Lavington East Public School',
    'Lavington Public School',
    'Lawrence Hargrave School',
    'Lawrence Public School',
    'Lawson Public School',
    'Leeton High School',
    'Leeton Public School',
    'Leeville Public School',
    'Leichhardt Public School',
    'Lennox Head Public School',
    'Leonay Public School',
    'Leppington Public School',
    'Les Powell School',
    'Lethbridge Park Public School',
    'Leumeah High School',
    'Leumeah Public School',
    'Leura Public School',
    'Lewisham Public School',
    'Lidcombe Public School',
    'Lightning Ridge Central School',
    'Lilli Pilli Public School',
    'Lincoln School',
    'Lindfield East Public School',
    'Lindfield Public School',
    'Lindsay Park Public School',
    'Lisarow High School',
    'Lisarow Public School',
    'Lismore Heights Public School',
    'Lismore High School',
    'Lismore Public School',
    'Lismore South Public School',
    'Lithgow High School',
    'Lithgow Public School',
    'Liverpool Boys High School',
    'Liverpool Girls High School',
    'Liverpool Hospital School',
    'Liverpool Public School',
    'Liverpool West Public School',
    'Llandilo Public School',
    'Lochinvar Public School',
    'Lockhart Central School',
    'Loftus Public School',
    'Lomandra School',
    'Londonderry Public School',
    'Long Flat Public School',
    'Longneck Lagoon Environmental Education Centre',
    'Lord Howe Island Central School',
    'Louth Public School',
    'Lowanna Public School',
    'Lowesdale Public School',
    'Lucas Gardens School',
    'Lucas Heights Community School',
    'Luddenham Public School',
    'Lue Public School',
    'Lugarno Public School',
    'Lurnea High School',
    'Lurnea Public School',
    'Lyndhurst Public School',
    'Lynwood Park Public School',
    'Macarthur Girls High School',
    'Macdonald Valley Public School',
    'Macintyre High School',
    'Macksville High School',
    'Macksville Public School',
    'Maclean High School',
    'Maclean Public School',
    'Macquarie Fields High School',
    'Macquarie Fields Public School',
    'Madang Avenue Public School',
    'Maimuru Public School',
    'Main Arm Upper Public School',
    'Mainsbridge School',
    'Maitland East Public School',
    'Maitland Grossmann High School',
    'Maitland High School',
    'Maitland Public School',
    'Malabar Public School',
    'Mallawa Public School',
    'Mandurama Public School',
    'Manifold Public School',
    'Manildra Public School',
    'Manilla Central School',
    'Manly Vale Public School',
    'Manly Village Public School',
    'Manly West Public School',
    'Mannering Park Public School',
    'Manning Gardens Public School',
    'Maraylya Public School',
    'Marayong Heights Public School',
    'Marayong Public School',
    'Marayong South Public School',
    'Marie Bashir Public School',
    'Marks Point Public School',
    'Maroota Public School',
    'Maroubra Bay Public School',
    'Maroubra Junction Public School',
    'Marra Creek Public School',
    'Marrar Public School',
    'Marrickville High School',
    'Marrickville Public School',
    'Marrickville West Public School',
    'Marsden High School',
    'Marsden Park Public School',
    'Marsden Road Public School',
    'Martindale Public School',
    'Martins Creek Public School',
    'Martins Gully Public School',
    'Marton Public School',
    'Marulan Public School',
    'Mary Brooksbank School',
    'Maryland Public School',
    'Mascot Public School',
    'Mathoura Public School',
    'Matong Public School',
    'Matraville Public School',
    'Matraville Soldiers Settlement Public School',
    'Matraville Sports High School',
    'Matthew Pearce Public School',
    'Mawarra Public School',
    'Mayfield East Public School',
    'Mayfield West Public School',
    'Mayrung Public School',
    'McCallums Hill Public School',
    'Meadow Flat Public School',
    'Meadowbank Public School',
    'Medlow Public School',
    'Medowie Public School',
    'Megalong Public School',
    'Melrose Park Public School',
    'Melville High School',
    'Menai High School',
    'Menai Public School',
    'Mendooran Central School',
    'Menindee Central School',
    'Merewether Heights Public School',
    'Merewether High School',
    'Merewether Public School',
    'Merimbula Public School',
    'Merriwa Central School',
    'Merrylands East Public School',
    'Merrylands High School',
    'Merrylands Public School',
    'Metella Road Public School',
    'Metford Public School',
    'Mian School',
    'Michelago Public School',
    'Middle Dural Public School',
    'Middle Harbour Public School',
    'Middleton Grange Public School',
    'Middleton Public School',
    'Milbrodale Public School',
    'Millbank Public School',
    'Miller High School',
    'Miller Public School',
    'Millers Forest Public School',
    'Millfield Public School',
    'Millthorpe Public School',
    'Milperra Public School',
    'Milton Public School',
    'Mimosa Public School',
    'Minchinbury Public School',
    'Minerva School',
    'Mingoola Public School',
    'Minmi Public School',
    'Minnamurra Public School',
    'Minto Public School',
    'Miranda North Public School',
    'Miranda Public School',
    'Mitchell High School',
    'Mitchells Island Public School',
    'Mittagong Public School',
    'Moama Public School',
    'Modanville Public School',
    'Model Farms High School',
    'Mogo Public School',
    'Molong Central School',
    'Mona Vale Public School',
    'Monaro High School',
    'Monteagle Public School',
    'Moonbi Public School',
    'Moorebank High School',
    'Moorefield Girls High School',
    'Moorland Public School',
    'Moree East Public School',
    'Moree Public School',
    'Moree Secondary College Albert Street Campus',
    'Moree Secondary College Carol Avenue Campus',
    'Morgan Street Public School',
    'Morisset High School',
    'Morisset Public School',
    'Morpeth Public School',
    'Mortdale Public School',
    'Mortlake Public School',
    'Moruya High School',
    'Moruya Public School',
    'Mosman High School',
    'Mosman Public School',
    'Moss Vale High School',
    'Moss Vale Public School',
    'Moulamein Public School',
    'Mount Annan High School',
    'Mount Annan Public School',
    'Mount Austin High School',
    'Mount Austin Public School',
    'Mount Brown Public School',
    'Mount Colah Public School',
    'Mount Druitt Public School',
    'Mount George Public School',
    'Mount Hunter Public School',
    'Mount Hutton Public School',
    'Mount Kanwary Public School',
    'Mount Keira Public School',
    'Mount Kembla Public School',
    'Mount Kuring-gai Public School',
    'Mount Lewis Infants School',
    'Mount Ousley Public School',
    'Mount Pleasant Public School',
    'Mount Pritchard East Public School',
    'Mount Pritchard Public School',
    'Mount Riverview Public School',
    'Mount St Thomas Public School',
    'Mount Terry Public School',
    'Mount Victoria Public School',
    'Mount View High School',
    'Mount Warrigal Public School',
    'Mowbray Public School',
    'Mudgee High School',
    'Mudgee Public School',
    'Muirfield High School',
    'Mulbring Public School',
    'Mulgoa Public School',
    'Mullaley Public School',
    'Mullaway Public School',
    'Mullengandra Public School',
    'Mullion Creek Public School',
    'Mullumbimby High School',
    'Mullumbimby Public School',
    'Mulwala Public School',
    'Mulwaree High School',
    'Mulyan Public School',
    'Mumbil Public School',
    'Mummulgum Public School',
    'Mungindi Central School',
    'Murray Farm Public School',
    'Murray High School',
    'Murringo Public School',
    'Murrumburrah High School',
    'Murrumburrah Public School',
    'Murrurundi Public School',
    'Murwillumbah East Public School',
    'Murwillumbah High School',
    'Murwillumbah Public School',
    'Murwillumbah South Infants School',
    'Muswellbrook High School',
    'Muswellbrook Public School',
    'Muswellbrook South Public School',
    'Nabiac Public School',
    'Nambucca Heads High School',
    'Nambucca Heads Public School',
    'Nana Glen Public School',
    'Nangus Public School',
    'Naradhan Public School',
    'Narara Public School',
    'Narara Valley High School',
    'Nareena Hills Public School',
    'Narellan Public School',
    'Narellan Vale Public School',
    'Naremburn School',
    'Narooma High School',
    'Narooma Public School',
    'Narrabeen Lakes Public School',
    'Narrabeen North Public School',
    'Narrabeen Sports High School',
    'Narrabri High School',
    'Narrabri Public School',
    'Narrabri West Public School',
    'Narrandera East Infants School',
    'Narrandera High School',
    'Narrandera Public School',
    'Narranga Public School',
    'Narraweena Public School',
    'Narromine High School',
    'Narromine Public School',
    'Narwee Public School',
    'Nashdale Public School',
    'Nemingha Public School',
    'Nepean Creative and Performing Arts High School',
    'Neutral Bay Public School',
    'Neville Public School',
    'New Lambton Heights Infants School',
    'New Lambton Public School',
    'New Lambton South Public School',
    'Newbridge Heights Public School',
    'Newcastle East Public School',
    'Newcastle High School',
    'Newcastle Junior School',
    'Newcastle Middle School',
    'Newcastle Senior School',
    'Newington Public School',
    'Newling Public School',
    'Newport Public School',
    'Newrybar Public School',
    'Newtown High School of Performing Arts',
    'Newtown North Public School',
    'Newtown Public School',
    'Niagara Park Public School',
    'Niangala Public School',
    'Nicholson Street Public School',
    'Niland School',
    'Nillo Infants School',
    'Nimbin Central School',
    'Nimmitabel Public School',
    'Nords Wharf Public School',
    'Norfolk Island Central School',
    'Normanhurst Boys High School',
    'Normanhurst Public School',
    'Normanhurst West Public School',
    'North East Public School of Distance Education',
    'North Gosford Learning Centre',
    'North Haven Public School',
    'North Nowra Public School',
    'North Rocks Public School',
    'North Ryde Public School',
    'North Star Public School',
    'North Sydney Boys High School',
    'North Sydney Girls High School',
    'North Sydney Public School',
    'North Wagga Public School',
    'Northbridge Public School',
    'Northern Beaches Secondary College Balgowlah Boys Campus',
    'Northern Beaches Secondary College Cromer Campus',
    'Northern Beaches Secondary College Freshwater Senior Campus',
    'Northern Beaches Secondary College Mackellar Girls Campus',
    'Northern Beaches Secondary College Manly Campus',
    'Northlakes High School',
    'Northlakes Public School',
    'Northmead Creative and Performing Arts High School',
    'Northmead Public School',
    'Noumea Public School',
    'Nowendoc Public School',
    'Nowra East Public School',
    'Nowra High School',
    'Nowra Hill Public School',
    'Nowra Public School',
    'Nulkaba Public School',
    'Numeralla Public School',
    'Nundle Public School',
    'Nuwarra Public School',
    'Nymboida Public School',
    'Nyngan High School',
    'Nyngan Public School',
    'Oak Flats High School',
    'Oak Flats Public School',
    'Oakdale Public School',
    'Oakhill Drive Public School',
    'Oaklands Central School',
    'Oakville Public School',
    'Oatlands Public School',
    'Oatley Public School',
    'Oatley West Public School',
    'Oberon High School',
    'Oberon Public School',
    'Observatory Hill Environmental Education Centre',
    'Ocean Shores Public School',
    'O\'\Connell Public School',
    'Old Bar Public School',
    'Old Bonalbo Public School',
    'Old Guildford Public School',
    'Open High School',
    'Orama Public School',
    'Oran Park Public School',
    'Orana Heights Public School',
    'Orange East Public School',
    'Orange Grove Public School',
    'Orange High School',
    'Orange Public School',
    'Orara High School',
    'Orara Upper Public School',
    'Orchard Hills Public School',
    'Otford Public School',
    'Ourimbah Public School',
    'Oxley High School',
    'Oxley Island Public School',
    'Oxley Park Public School',
    'Oxley Vale Public School',
    'Oyster Bay Public School',
    'Pacific Palms Public School',
    'Paddington Public School',
    'Padstow Heights Public School',
    'Padstow North Public School',
    'Padstow Park Public School',
    'Pagewood Public School',
    'Palinyewah Public School',
    'Pallamallawa Public School',
    'Palm Avenue School',
    'Palmers Island Public School',
    'Pambula Public School',
    'Panania North Public School',
    'Panania Public School',
    'Para Meadows School',
    'Parkes East Public School',
    'Parkes High School',
    'Parkes Public School',
    'Parklea Public School',
    'Parkview Public School',
    'Parramatta East Public School',
    'Parramatta High School',
    'Parramatta North Public School',
    'Parramatta Public School',
    'Parramatta West Public School',
    'Parry School',
    'Passfield Park School',
    'Paterson Public School',
    'Paxton Public School',
    'Peak Hill Central School',
    'Peakhurst Public School',
    'Peakhurst South Public School',
    'Peakhurst West Public School',
    'Peats Ridge Public School',
    'Peel High School',
    'Pelaw Main Public School',
    'Pelican Flat Public School',
    'Pendle Hill High School',
    'Pendle Hill Public School',
    'Pennant Hills High School',
    'Pennant Hills Public School',
    'Penrith High School',
    'Penrith Lakes Environmental Education Centre',
    'Penrith Public School',
    'Penrith South Public School',
    'Penrith Valley Learning Centre',
    'Penrose Public School',
    'Penshurst Public School',
    'Penshurst West Public School',
    'Perthville Public School',
    'Peterborough School',
    'Petersham Public School',
    'Picnic Point High School',
    'Picnic Point Public School',
    'Picton High School',
    'Picton Public School',
    'Pilliga Public School',
    'Pitt Town Public School',
    'Pittwater High School',
    'Plattsburg Public School',
    'Pleasant Heights Public School',
    'Pleasant Hills Public School',
    'Plumpton High School',
    'Plumpton House School',
    'Plumpton Public School',
    'Plunkett Street Public School',
    'Point Clare Public School',
    'Pomona Public School',
    'Port Hacking High School',
    'Port Kembla Public School',
    'Port Macquarie High School',
    'Port Macquarie Public School',
    'Portland Central School',
    'Pottsville Beach Public School',
    'Prairievale Public School',
    'Prairiewood High School',
    'Premer Public School',
    'Prestons Public School',
    'Pretty Beach Public School',
    'Primbee Public School',
    'Punchbowl Boys High School',
    'Punchbowl Public School',
    'Putland School',
    'Putney Public School',
    'Pymble Public School',
    'Quaama Public School',
    'Quakers Hill East Public School',
    'Quakers Hill High School',
    'Quakers Hill Public School',
    'Quambone Public School',
    'Quandialla Central School',
    'Queanbeyan East Public School',
    'Queanbeyan High School',
    'Queanbeyan Public School',
    'Queanbeyan South Public School',
    'Queanbeyan West Public School',
    'Quirindi High School',
    'Quirindi Public School',
    'Raglan Public School',
    'Railway Town Public School',
    'Rainbow Street Public School',
    'Raleigh Public School',
    'Ramsgate Public School',
    'Rand Public School',
    'Randwick Boys High School',
    'Randwick Girls High School',
    'Randwick Public School',
    'Rankins Springs Public School',
    'Rappville Public School',
    'Rathmines Public School',
    'Raymond Terrace Public School',
    'Red Hill Environmental Education Centre',
    'Red Range Public School',
    'Redbank School',
    'Redhead Public School',
    'Regents Park Public School',
    'Regentville Public School',
    'Repton Public School',
    'Revesby Public School',
    'Revesby South Public School',
    'Richmond High School',
    'Richmond North Public School',
    'Richmond Public School',
    'Richmond River High School',
    'Ringrose Public School',
    'Rivendell School',
    'Riverbank Public School',
    'Riverina Environmental Education Centre',
    'Riverside Girls High School',
    'Riverstone High School',
    'Riverstone Public School',
    'Riverwood Public School',
    'Robert Townson High School',
    'Robert Townson Public School',
    'Robertson Public School',
    'Rockdale Public School',
    'Rockley Public School',
    'Rocky River Public School',
    'Rollands Plains Upper Public School',
    'Rooty Hill High School',
    'Rooty Hill Public School',
    'Ropes Crossing Public School',
    'Rose Bay Public School',
    'Rose Bay Secondary College',
    'Rosebank Public School',
    'Rosehill Public School',
    'Roselea Public School',
    'Rosemeadow Public School',
    'Roseville Public School',
    'Rosewood Public School',
    'Ross Hill Public School',
    'Rossmore Public School',
    'Rous Public School',
    'Rouse Hill High School',
    'Rouse Hill Public School',
    'Rowena Public School',
    'Rowland Hassall School',
    'Royal Far West School',
    'Royal National Park Environmental Education Centre',
    'Royal North Shore Hospital School',
    'Royal Prince Alfred Hospital School',
    'Rozelle Public School',
    'Rugby Public School',
    'Rukenvale Public School',
    'Rumbalara Environmental Education Centre',
    'Ruse Public School',
    'Russell Lea Infants School',
    'Russell Vale Public School',
    'Rutherford High School',
    'Rutherford Public School',
    'Rydalmere East Public School',
    'Rydalmere Public School',
    'Ryde East Public School',
    'Ryde Public School',
    'Ryde Secondary College',
    'Rye Park Public School',
    'Rylstone Public School',
    'Sackville Street Public School',
    'Sadleir Public School',
    'Salt Ash Public School',
    'Samuel Gilbert Public School',
    'Samuel Terry Public School',
    'Sanctuary Point Public School',
    'Sandon Public School',
    'Sandy Beach Public School',
    'Sandy Hollow Public School',
    'Sans Souci Public School',
    'Sarah Redfern High School',
    'Sarah Redfern Public School',
    'Saturday School of Community Languages',
    'Savernake Public School',
    'Sawtell Public School',
    'Scarborough Public School',
    'Schofields Public School',
    'School of the Air',
    'Scone High School',
    'Scone Public School',
    'Scotts Head Public School',
    'Seaforth Public School',
    'Seaham Public School',
    'Sefton High School',
    'Sefton Infants School',
    'Seven Hills High School',
    'Seven Hills North Public School',
    'Seven Hills Public School',
    'Seven Hills West Public School',
    'Shalvey Public School',
    'Shell Cove Public School',
    'Shelley Public School',
    'Shellharbour Public School',
    'Shepherds Park School',
    'Sherwood Grange Public School',
    'Sherwood Ridge Public School',
    'Shoal Bay Public School',
    'Shoalhaven Heads Public School',
    'Shoalhaven High School',
    'Shortland Public School',
    'Singleton Heights Public School',
    'Singleton High School',
    'Singleton Public School',
    'Sir Eric Woodward Memorial School',
    'Sir Joseph Banks High School',
    'Smithfield Public School',
    'Smithfield West Public School',
    'Smiths Hill High School',
    'Smithtown Public School',
    'Sofala Public School',
    'Soldiers Point Public School',
    'Somersby Public School',
    'Somerton Public School',
    'South Coogee Public School',
    'South Grafton High School',
    'South Grafton Public School',
    'South Sydney High School',
    'South Wagga Public School',
    'South West Rocks Public School',
    'Southern Cross School',
    'Speers Point Public School',
    'Spencer Public School',
    'Spring Hill Public School',
    'Spring Ridge Public School',
    'Spring Terrace Public School',
    'Springdale Heights Public School',
    'Springwood High School',
    'Springwood Public School',
    'St Andrews Public School',
    'St Clair High School',
    'St Clair Public School',
    'St George Girls High School',
    'St George Hospital School',
    'St George School',
    'St Georges Basin Public School',
    'St Helens Park Public School',
    'St Ives High School',
    'St Ives North Public School',
    'St Ives Park Public School',
    'St Ives Public School',
    'St Johns Park High School',
    'St Johns Park Public School',
    'St Marys North Public School',
    'St Marys Public School',
    'St Marys Senior High School',
    'St Marys South Public School',
    'St Peters Public School',
    'Stanford Merthyr Infants School',
    'Stanmore Public School',
    'Stanwell Park Public School',
    'Stewart House School',
    'Stockinbingal Public School',
    'Stockton Public School',
    'Stokers Siding Public School',
    'Stratford Public School',
    'Stratheden Public School',
    'Strathfield Girls High School',
    'Strathfield North Public School',
    'Strathfield South High School',
    'Strathfield South Public School',
    'Stroud Public School',
    'Stroud Road Public School',
    'Stuart Town Public School',
    'Stuarts Point Public School',
    'Sturt Public School',
    'Summer Hill Public School',
    'Sunning Hill School',
    'Sunshine Bay Public School',
    'Surveyors Creek Public School',
    'Sussex Inlet Public School',
    'Sutherland Hospital School',
    'Sutherland North Public School',
    'Sutherland Public School',
    'Sutton Public School',
    'Swansea High School',
    'Swansea Public School',
    'Sydney Boys High School',
    'Sydney Childrens Hospital School',
    'Sydney Distance Education High School',
    'Sydney Distance Education Primary School',
    'Sydney Girls High School',
    'Sydney Secondary College Balmain Campus',
    'Sydney Secondary College Blackwattle Bay Campus',
    'Sydney Secondary College Leichhardt Campus',
    'Sydney Technical High School',
    'Sylvania Heights Public School',
    'Sylvania High School',
    'Sylvania Public School',
    'Table Top Public School',
    'Tabulam Public School',
    'Tacking Point Public School',
    'Tacoma Public School',
    'Tahmoor Public School',
    'Talbingo Public School',
    'Tallimba Public School',
    'Tallong Public School',
    'Tallowood School',
    'Tambar Springs Public School',
    'Tamworth High School',
    'Tamworth Public School',
    'Tamworth South Public School',
    'Tamworth West Public School',
    'Tangara School',
    'Tanilba Bay Public School',
    'Tanja Public School',
    'Tarago Public School',
    'Taralga Public School',
    'Tarcutta Public School',
    'Taree High School',
    'Taree Public School',
    'Taree West Public School',
    'Taren Point Public School',
    'Tarrawanna Public School',
    'Tarro Public School',
    'Tathra Public School',
    'Taverners Hill Infants School',
    'Tea Gardens Public School',
    'Telarah Public School',
    'Telegraph Point Public School',
    'Telopea Public School',
    'Temora High School',
    'Temora Public School',
    'Temora West Public School',
    'Tempe High School',
    'Tempe Public School',
    'Tenambit Public School',
    'Tenterfield High School',
    'Teralba Public School',
    'Terara Public School',
    'Terranora Public School',
    'Terrey Hills Public School',
    'Terrigal High School',
    'Terrigal Public School',
    'Teven-Tintenbar Public School',
    'Thalgarrah Environmental Education Centre',
    'Tharawal Public School',
    'Tharbogang Public School',
    'The Beach School',
    'The Bidgee School',
    'The Channon Public School',
    'The Childrens Hospital School',
    'The Crescent School',
    'The Entrance Public School',
    'The Forest High School',
    'The Grange Public School',
    'The Henry Lawson High School',
    'The Hills School',
    'The Hills Sports High School',
    'The Jannali High School',
    'The Junction Public School',
    'The Meadows Public School',
    'The Oaks Public School',
    'The Pocket Public School',
    'The Ponds High School',
    'The Ponds School',
    'The Risk Public School',
    'The Rock Central School',
    'The Sir Henry Parkes Memorial Public School',
    'Thirlmere Public School',
    'Thirroul Public School',
    'Thomas Acres Public School',
    'Thomas Reddall High School',
    'Thornleigh West Public School',
    'Thornton Public School',
    'Thurgoona Public School',
    'Tibooburra Outback Public School',
    'Tighes Hill Public School',
    'Timbumburi Public School',
    'Tingha Public School',
    'Tinonee Public School',
    'Tintinhull Public School',
    'Tirranna Public School',
    'Tocumwal Public School',
    'Tolland Public School',
    'Tomaree High School',
    'Tomaree Public School',
    'Tomerong Public School',
    'Tooleybuc Central School',
    'Toomelah Public School',
    'Toongabbie East Public School',
    'Toongabbie Public School',
    'Toongabbie West Public School',
    'Tooraweenah Public School',
    'Toormina High School',
    'Toormina Public School',
    'Toronto High School',
    'Toronto Public School',
    'Tottenham Central School',
    'Toukley Public School',
    'Towamba Public School',
    'Tower Street Public School',
    'Towradgi Public School',
    'Trangie Central School',
    'Tregeagle Public School',
    'Tregear Public School',
    'Trundle Central School',
    'Trunkey Public School',
    'Truscott Street Public School',
    'Tucabia Public School',
    'Tuggerah Lakes Secondary College Berkeley Vale Campus',
    'Tuggerah Lakes Secondary College The Entrance Campus',
    'Tuggerah Lakes Secondary College Tumbi Umbi Campus',
    'Tuggerah Public School',
    'Tuggerawong Public School',
    'Tullamore Central School',
    'Tullibigeal Central School',
    'Tullimbar Public School',
    'Tulloona Public School',
    'Tumbarumba High School',
    'Tumbarumba Public School',
    'Tumbulgum Public School',
    'Tumut High School',
    'Tumut Public School',
    'Tuncurry Public School',
    'Tuntable Creek Public School',
    'Turramurra High School',
    'Turramurra North Public School',
    'Turramurra Public School',
    'Turvey Park Public School',
    'Tweed Heads Public School',
    'Tweed Heads South Public School',
    'Tweed River High School',
    'Tyalgum Public School',
    'Tyalla Public School',
    'Uki Public School',
    'Ulan Public School',
    'Ulladulla High School',
    'Ulladulla Public School',
    'Ulmarra Public School',
    'Ulong Public School',
    'Ultimo Public School',
    'Umina Public School',
    'Unanderra Public School',
    'Undercliffe Public School',
    'Ungarie Central School',
    'Upper Coopers Creek Public School',
    'Upper Lansdowne Public School',
    'Uralla Central School',
    'Urana Public School',
    'Uranquinty Public School',
    'Urbenville Public School',
    'Urunga Public School',
    'Vacy Public School',
    'Valentine Public School',
    'Valley View Public School',
    'Vardys Road Public School',
    'Vaucluse Public School',
    'Verona School',
    'Victoria Avenue Public School',
    'Villawood East Public School',
    'Villawood North Public School',
    'Vincentia High School',
    'Vincentia Public School',
    'Vineyard Public School',
    'Wadalba Community School',
    'Wade High School',
    'Wagga Wagga High School',
    'Wagga Wagga Public School',
    'Wahroonga Public School',
    'Wairoa School',
    'Waitara Public School',
    'Wakefield School',
    'Wakehurst Public School',
    'Wakool Burraboi Public School',
    'Walbundrie Public School',
    'Walcha Central School',
    'Walgett Community College - High School',
    'Walgett Community College - Primary School',
    'Walhallow Public School',
    'Walla Walla Public School',
    'Wallabadah Public School',
    'Wallacia Public School',
    'Wallendbeen Public School',
    'Wallerawang Public School',
    'Wallsend Public School',
    'Wallsend South Public School',
    'Walters Road Public School',
    'Wambangalang Environmental Education Centre',
    'Wamberal Public School',
    'Wamoon Public School',
    'Wanaaring Public School',
    'Wangee Park School',
    'Wangi Wangi Public School',
    'Waniora Public School',
    'Waratah Public School',
    'Waratah West Public School',
    'Wardell Public School',
    'Warialda High School',
    'Warialda Public School',
    'Warilla High School',
    'Warilla North Public School',
    'Warilla Public School',
    'Warners Bay High School',
    'Warners Bay Public School',
    'Warnervale Public School',
    'Warragamba Public School',
    'Warrawee Public School',
    'Warrawong High School',
    'Warrawong Public School',
    'Warren Central School',
    'Warrimoo Public School',
    'Warrumbungle National Park Environmental Education Centre',
    'Warwick Farm Public School',
    'Waterfall Public School',
    'Wattawa Heights Public School',
    'Wattle Flat Public School',
    'Wattle Grove Public School',
    'Wauchope High School',
    'Wauchope Public School',
    'Waverley Public School',
    'Wee Jasper Public School',
    'Wee Waa High School',
    'Wee Waa Public School',
    'Weethalle Public School',
    'Weilmoringle Public School',
    'Wellington High School',
    'Wellington Public School',
    'Wentworth Falls Public School',
    'Wentworth Public School',
    'Wentworthville Public School',
    'Werrington County Public School',
    'Werrington Public School',
    'Werris Creek Public School',
    'West Pennant Hills Public School',
    'West Pymble Public School',
    'West Ryde Public School',
    'West Wallsend High School',
    'West Wallsend Public School',
    'West Wyalong High School',
    'West Wyalong Public School',
    'Westdale Public School',
    'Westfields Sports High School',
    'Westlawn Public School',
    'Westmead Public School',
    'Weston Public School',
    'Westport High School',
    'Westport Public School',
    'Wetlands Environmental Education Centre',
    'Wewak Street School',
    'Whalan Public School',
    'Wheeler Heights Public School',
    'Whian Whian Public School',
    'White Cliffs Public School',
    'Whitebridge High School',
    'Whitton Public School',
    'Wiangaree Public School',
    'Widemere Public School',
    'Wideview Public School',
    'Wilberforce Public School',
    'Wilcannia Central School',
    'Wiley Park Girls High School',
    'Wiley Park Public School',
    'Wilkins Public School',
    'Willans Hill School',
    'Willawarrin Public School',
    'William Bayldon Public School',
    'William Dean Public School',
    'William Rose School',
    'William Stimson Public School',
    'Willmot Public School',
    'Willoughby Girls High School',
    'Willoughby Public School',
    'Willow Tree Public School',
    'Willyama High School',
    'Wilson Park School',
    'Wilsons Creek Public School',
    'Wilton Public School',
    'Windale Public School',
    'Windang Public School',
    'Windellama Public School',
    'Windsor High School',
    'Windsor Park Public School',
    'Windsor Public School',
    'Windsor South Public School',
    'Wingello Public School',
    'Wingham Brush Public School',
    'Wingham High School',
    'Wingham Public School',
    'Winmalee High School',
    'Winmalee Public School',
    'Winston Heights Public School',
    'Winston Hills Public School',
    'Wiripaang Public School',
    'Wirreanda Public School',
    'Wisemans Ferry Public School',
    'Wollar Public School',
    'Wollondilly Public School',
    'Wollongbar Public School',
    'Wollongong High School of the Performing Arts',
    'Wollongong Public School',
    'Wollongong West Public School',
    'Wollumbin High School',
    'Wolumla Public School',
    'Wombat Public School',
    'Wongarbon Public School',
    'Woniora Road School',
    'Woodberry Learning Centre',
    'Woodberry Public School',
    'Woodburn Public School',
    'Woodenbong Central School',
    'Woodland Road Public School',
    'Woodport Public School',
    'Woodstock Public School',
    'Wooglemai Environmental Education Centre',
    'Woolbrook Public School',
    'Woolgoolga High School',
    'Woolgoolga Public School',
    'Wooli Public School',
    'Woollahra Public School',
    'Woolomin Public School',
    'Woolooware High School',
    'Woolooware Public School',
    'Woongarrah Public School',
    'Woonona East Public School',
    'Woonona High School',
    'Woonona Public School',
    'Woronora River Public School',
    'Woy Woy Public School',
    'Woy Woy South Public School',
    'Wyalong Public School',
    'Wyangala Dam Public School',
    'Wyee Public School',
    'Wyndham College',
    'Wyndham Public School',
    'Wyoming Public School',
    'Wyong Creek Public School',
    'Wyong High School',
    'Wyong Public School',
    'Wyrallah Public School',
    'Wyrallah Road Public School',
    'Wytaliba Public School',
    'Yagoona Public School',
    'Yamba Public School',
    'Yanco Agricultural High School',
    'Yanco Public School',
    'Yanderra Public School',
    'Yarrawarrah Public School',
    'Yarrowitch Public School',
    'Yass High School',
    'Yass Public School',
    'Yates Avenue Public School',
    'Yenda Public School',
    'Yennora Public School',
    'Yeo Park Infants School',
    'Yeoval Central School',
    'Yerong Creek Public School',
    'Yetman Public School',
    'Yoogali Public School',
    'York Public School',
    'Young High School',
    'Young North Public School',
    'Young Public School',
    'Yowie Bay Public School',
    'Zig Zag Public School'
        ];
        var names = [];
        for (var i = 0; i < 2215; i++) {
            names.push(schoolArray[i]);
        };
        return names;
    }());
    
	
    // kick it off
    var nrwr = new Narrower(inp, sel, disp, list);
    nrwr.init();
}(this, this.document));

$(document).ready(function(){
	// Initialize collapse button
	$('.button-collapse').sideNav({
      menuWidth: 300, // Default is 240
      edge: 'left', // Choose the horizontal origin
      closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    }
  	);

    //Global variables
	var saveisChecked = 0;
	var fNameStorage = 0;
	var lNameStorage = 0;
	var emailStorage = 0;
	var schoolStorage = 0;
	var isthereData = 0;

    //Get and Write Storage Data
	getDataWriteData();


    //Reset form after Submit
	function partialReset() {
	    isthereData = window.localStorage.getItem("isthereData");
	    $('textarea').val('');
	    $('input').val('');
	    $('input:checkbox').removeAttr('checked');
	    $("input").blur();
	    $("textarea").blur();
        getDataWriteData();

	};

    //Clear Storage Function
	function deleteinformation() {
	    isthereData = window.localStorage.getItem("isthereData");
	    if (isthereData == 1) {
	        //Remove all Items from Storage
	        window.localStorage.removeItem("isthereData");
	        window.localStorage.removeItem("fName");
	        window.localStorage.removeItem("lName");
	        window.localStorage.removeItem("email");
	        window.localStorage.removeItem("school");

	        //Remove Text Value from Input Boxes
	        $('input[name="firstNameInput"]').val("");
	        $('input[name="lastNameInput"]').val("");
	        $('input[name="emailInput"]').val("");
	        $('input[name="schoolInput"]').val("");
	        //Remove Focus so Inputs are Back to Normal
	        $("input").blur();
	        $("textarea").blur();
	    };
	};

    //Check if there is data, if not the command will end.
	function getDataWriteData() {
	    isthereData = window.localStorage.getItem("isthereData");
	    if (isthereData == 1) {

	        //Get Data from Storage
	        var firstNamefromStorage = window.localStorage.getItem("fName");
	        var lastNamefromStorage = window.localStorage.getItem("lName");
	        var emailfromStorage = window.localStorage.getItem("email");
	        var schoolfromStorage = window.localStorage.getItem("school");

	        //Input Data into Value of Input
	        $('input[name="firstNameInput"]').val(firstNamefromStorage);
	        $('input[name="lastNameInput"]').val(lastNamefromStorage);
	        $('input[name="emailInput"]').val(emailfromStorage);
	        $('input[name="schoolInput"]').val(schoolfromStorage);

            //Add Focus so Text Doesn't Overlap
	        $('input[name="firstNameInput"]').focus();
	        $('input[name="lastNameInput"]').focus();
	        $('input[name="emailInput"]').focus();
	        $('input[name="schoolInput"]').focus();
	    };
	};

    //EVENT LISTENERS
    //Trigger change of variable if saveinfo is checked
	$('#saveinfo').change(function () {
	    saveisChecked = 1;
	});

    //Check if the user wants to save data, if so, save it when submitting the form.
	$('#submitButton').click(function () {
	    if (saveisChecked == 1) {
	        window.localStorage.setItem("isthereData", 1);

	        //Get value data from Inputs
	        fNameStorage = $('input[name="firstNameInput"]').val();
	        lNameStorage = $('input[name="lastNameInput"]').val();
	        emailStorage = $('input[name="emailInput"]').val();
	        schoolStorage = $('input[name="schoolInput"]').val();

	        //Save Value data into Storage
	        window.localStorage.setItem("fName", fNameStorage);
	        window.localStorage.setItem("lName", lNameStorage);
	        window.localStorage.setItem("email", emailStorage);
	        window.localStorage.setItem("school", schoolStorage);
	    };
	    sendEmail();
	    partialReset();
	});

    //Run Clear Storage Function on click of button
	$('#clearinfo').click(function () {
	    deleteinformation();
	});

    //End Code for Form Storage
});

//Initialize the email plugin
document.addEventListener('deviceready', function () {
    // cordova.plugins.email is now available
}, false);

cordova.plugins.email.isAvailable(
    function (isAvailable) {
        // alert('Service is not available') unless isAvailable;
    }
);
//Variables for Input Values
var firstName = 0;
var lastName = 0;
var email = 0;
var message = 0;
var toSchool = 0;


//Send Email Function
function sendEmail() {
    //Pull Data from Input
    firstName = $('input[name="firstNameInput"]').val();
    lastName = $('input[name="lastNameInput"]').val();
    email = $('input[name="emailInput"]').val();
    message = $('textarea[name="messagetoDepartment"]').val();

    //Send Email
    alert('Are you sure you want to send this email?');
    cordova.plugins.email.open({
        app: 'gmail',
        to: toSchool,
        cc: '',
        bcc: ['halfbeardstudios@gmail.com',email],
        subject: 'Student-Voice email from: ' + firstName + ' ' + lastName,
        body: message
    });
};

